// This file is auto-generated by @hey-api/openapi-ts

import { type Options, uploadMedia, createFood, getCategory, createCategory } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { UploadMediaData, UploadMediaResponse, CreateFoodData, CreateFoodResponse, GetCategoryData, CreateCategoryData, CreateCategoryResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const uploadMediaQueryKey = (options: Options<UploadMediaData>) => createQueryKey('uploadMedia', options);

export const uploadMediaOptions = (options: Options<UploadMediaData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await uploadMedia({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: uploadMediaQueryKey(options)
    });
};

export const uploadMediaMutation = (options?: Partial<Options<UploadMediaData>>): UseMutationOptions<UploadMediaResponse, DefaultError, Options<UploadMediaData>> => {
    const mutationOptions: UseMutationOptions<UploadMediaResponse, DefaultError, Options<UploadMediaData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await uploadMedia({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createFoodQueryKey = (options: Options<CreateFoodData>) => createQueryKey('createFood', options);

export const createFoodOptions = (options: Options<CreateFoodData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createFood({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createFoodQueryKey(options)
    });
};

export const createFoodMutation = (options?: Partial<Options<CreateFoodData>>): UseMutationOptions<CreateFoodResponse, DefaultError, Options<CreateFoodData>> => {
    const mutationOptions: UseMutationOptions<CreateFoodResponse, DefaultError, Options<CreateFoodData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createFood({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCategoryQueryKey = (options?: Options<GetCategoryData>) => createQueryKey('getCategory', options);

export const getCategoryOptions = (options?: Options<GetCategoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategory({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCategoryQueryKey(options)
    });
};

export const createCategoryQueryKey = (options: Options<CreateCategoryData>) => createQueryKey('createCategory', options);

export const createCategoryOptions = (options: Options<CreateCategoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createCategory({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createCategoryQueryKey(options)
    });
};

export const createCategoryMutation = (options?: Partial<Options<CreateCategoryData>>): UseMutationOptions<CreateCategoryResponse, DefaultError, Options<CreateCategoryData>> => {
    const mutationOptions: UseMutationOptions<CreateCategoryResponse, DefaultError, Options<CreateCategoryData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createCategory({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};