// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { UploadMediaData, UploadMediaResponse, CreateFoodData, CreateFoodResponse, GetCategoryData, GetCategoryResponse, CreateCategoryData, CreateCategoryResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const uploadMedia = <ThrowOnError extends boolean = false>(options: Options<UploadMediaData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UploadMediaResponse, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/media',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

export const createFood = <ThrowOnError extends boolean = false>(options: Options<CreateFoodData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateFoodResponse, unknown, ThrowOnError>({
        url: '/food',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getCategory = <ThrowOnError extends boolean = false>(options?: Options<GetCategoryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCategoryResponse, unknown, ThrowOnError>({
        url: '/category',
        ...options
    });
};

export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCategoryResponse, unknown, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/category',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};