// This file is auto-generated by @hey-api/openapi-ts

export type _36EnumsMediaType = 'CATEGORY_IMAGE' | 'FOOD_IMAGE';

export type CreateFoodDto = {
    name: string;
    price: number;
    quantity: number;
    image: number;
    spicyness?: boolean;
    category: number;
};

export type UploadMediaData = {
    body: {
        file: Blob | File;
        type: string;
    };
    path?: never;
    query?: never;
    url: '/media';
};

export type UploadMediaResponses = {
    /**
     * Ok
     */
    200: {
        categoryId: number;
        foodId: number;
        updatedAt: string;
        createdAt: string;
        mediaType: _36EnumsMediaType;
        name: string;
        id: number;
    } 
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type CreateFoodData = {
    body: CreateFoodDto;
    path?: never;
    query?: never;
    url: '/food';
};

export type CreateFoodResponses = {
    /**
     * Ok
     */
    200: {
        data: {
            isAvailable: boolean;
            quantity: number;
            price: number;
            hasSpicyness: boolean;
            categoryId: number;
            updatedAt: string;
            createdAt: string;
            name: string;
            id: number;
        };
        message: string;
        status: number;
    };
};

export type CreateFoodResponse = CreateFoodResponses[keyof CreateFoodResponses];

export type GetCategoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/category';
};

export type GetCategoryResponses = {
    /**
     * Ok
     */
    200: Array<{
        thumbnail: {
            categoryId: number;
            foodId: number;
            updatedAt: string;
            createdAt: string;
            mediaType: _36EnumsMediaType;
            name: string;
            id: number;
        };
    } & {
        createdAt: string;
        name: string;
        id: number;
    }>;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type CreateCategoryData = {
    body: {
        name: string;
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/category';
};

export type CreateCategoryResponses = {
    /**
     * Ok
     */
    200: {
        createdAt: string;
        name: string;
        id: number;
    };
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};